env:
  node: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  no-control-regex:
    - 0
  no-console:
    - off
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
